"""v2.8.0 — login brute-force throttle (zero-migration, DB-backed).

Django's admin ships with unlimited login attempts. On a public URL that is
an invitation for password spraying. This module keeps a rolling window of
failed attempts in a tiny table inside the private `django_admin` schema
(created lazily — no migration file needed) and blocks further attempts for
LOCKOUT_MINUTES once MAX_ATTEMPTS failures stack up for the same username
or the same source IP.

Design notes:
- Failures are recorded via Django's `user_login_failed` signal, so every
  authentication path through the admin login is covered.
- The lockout check runs BEFORE authentication: during a lockout even a
  correct password is rejected (standard back-off semantics).
- Old rows are pruned opportunistically; the table stays tiny.
"""
from django.db import connection

MAX_ATTEMPTS = 5
LOCKOUT_MINUTES = 15
_PRUNE_AFTER_DAYS = 2


def _ensure_table(cur) -> None:
    cur.execute(
        "create table if not exists django_admin.login_throttle ("
        "id bigint generated by default as identity primary key, "
        "username text not null default '', "
        "ip text not null default '', "
        "created_at timestamptz not null default now())")
    cur.execute(
        "create index if not exists login_throttle_lookup "
        "on django_admin.login_throttle (username, ip, created_at)")


def record_failure(username: str, ip: str) -> None:
    """Append one failed attempt (signal handler)."""
    try:
        with connection.cursor() as cur:
            _ensure_table(cur)
            cur.execute(
                "insert into django_admin.login_throttle (username, ip) "
                "values (%s, %s)", [(username or "")[:150], (ip or "")[:60]])
            # opportunistic prune — keep the table tiny
            cur.execute(
                "delete from django_admin.login_throttle "
                "where created_at < now() - interval %s",
                [f"{_PRUNE_AFTER_DAYS} days"])
    except Exception:
        # throttling must never take the login page down
        pass


def is_locked(username: str, ip: str) -> bool:
    """True when MAX_ATTEMPTS+ failures exist for this username OR this IP
    inside the lockout window."""
    try:
        with connection.cursor() as cur:
            _ensure_table(cur)
            cur.execute(
                "select count(*) from django_admin.login_throttle "
                "where created_at > now() - interval %s "
                "and (username = %s or ip = %s)",
                [f"{LOCKOUT_MINUTES} minutes", (username or "")[:150],
                 (ip or "")[:60]])
            row = cur.fetchone()
        return bool(row and row[0] and int(row[0]) >= MAX_ATTEMPTS)
    except Exception:
        return False


def failures_in_window(username: str, ip: str) -> int:
    """Current failure count (for messaging/diagnostics)."""
    try:
        with connection.cursor() as cur:
            _ensure_table(cur)
            cur.execute(
                "select count(*) from django_admin.login_throttle "
                "where created_at > now() - interval %s "
                "and (username = %s or ip = %s)",
                [f"{LOCKOUT_MINUTES} minutes", (username or "")[:150],
                 (ip or "")[:60]])
            row = cur.fetchone()
        return int(row[0]) if row and row[0] else 0
    except Exception:
        return 0
